language: node_js
node_js:
  - "8.12.0"

before_install: true
install: npm install

before_script: true
script: npm test

before_deploy: ./scripts/before_deploy.sh
deploy:
  provider: pages
  local_dir: gh-pages
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $TRAVIS_GHP
  keep_history: true
  on:
    branch: master